name: elogbook
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

assets:
  - .env

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.34.5
  flutter_dotenv: ^5.2.1
  flutter_foreground_task: ^8.17.0
  flutter_local_notifications: ^18.0.1
  flutter_riverpod: ^2.6.1
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  http: ^1.2.2
  intl: ^0.20.1
  objectbox: ^4.0.3
  objectbox_flutter_libs: any
  path: ^1.9.0
  path_provider: ^2.1.5
  path_provider_android: ^2.2.15
  path_provider_foundation: ^2.4.1
  permission_handler: ^11.3.1
  riverpod: ^2.6.1
  shared_preferences: ^2.3.5
  sqflite: ^2.4.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.9.0
  build_runner: ^2.4.14
  objectbox_generator: any

flutter:
  uses-material-design: true
